In [2]:
import numpy as np

##### **Assumptions:** The pivots are in the diagonal and edge cases are not yet addressed

In [3]:
def gaussianElimination(matrix):
    matrix = matrix.astype('float')
    num_rows = matrix.shape[0]
    for pivot in range(num_rows-1):   #pivot
        for row in range(pivot + 1, num_rows):  #succeeding row
            #subtract the current row by the pivot row (scaled by a factor) to result in a zero
            matrix[row] = matrix[row] - matrix[row, pivot] / matrix[pivot, pivot] * matrix[pivot]
    return matrix

In [6]:
matrix = np.array([[-3, 0, 1], [-2, 1, 3], [-2, -1, 0]]) #sample matrix
print(matrix)

[[-3  0  1]
 [-2  1  3]
 [-2 -1  0]]


In [7]:
gaussianElimination(matrix)


array([[-3.        ,  0.        ,  1.        ],
       [ 0.        ,  1.        ,  2.33333333],
       [ 0.        ,  0.        ,  1.66666667]])