In [1]:
import numpy as np
np.set_printoptions(precision=3, suppress=True) # Round the results to 3 decimal place

In [41]:
def householderHessenberg(matrix):
    A = matrix.astype('float')
    num_rows, num_columns = matrix.shape
    I = np.identity(num_rows)
    A_hut = np.copy(A) # initial hessenberg matrix
    for column in range(num_columns-2):
        x = np.vstack((np.zeros((column+1,1)), A_hut[column+1:, column].reshape(-1,1))) # append zero above the target row
        # change the operation depending on the sign
        if np.sign(x[column+1]) == 0 or np.sign(x[column+1]) == 1:
            x[column+1] += np.linalg.norm(x)
        else:
            x[column+1] -= np.linalg.norm(x)
        u = x/np.linalg.norm(x) # normalize
        H = I - 2*u@u.T # householder reflection
        A_hut = H @ A_hut @ H
        print(f'H{column+1}')
        print(H)
    return A_hut
    

In [42]:
# matrix = np.array([[1, 0, 2, 3], [-1, 0, 5, 2], [2, -2, 0, 0], [2, -1, 2, 0]]) # sample matrix
matrix = np.random.randint(0, 10, size=(4, 4))
print('Original Matrix\n', matrix)

Original Matrix
 [[1 7 2 8]
 [7 4 1 3]
 [3 0 1 5]
 [7 1 8 0]]


In [43]:
hess = householderHessenberg(matrix)

H1
[[ 1.     0.     0.     0.   ]
 [ 0.    -0.677 -0.29  -0.677]
 [ 0.    -0.29   0.95  -0.117]
 [ 0.    -0.677 -0.117  0.727]]
H2
[[ 1.     0.     0.     0.   ]
 [ 0.     1.     0.     0.   ]
 [ 0.     0.    -0.713  0.701]
 [ 0.     0.     0.701  0.713]]


In [44]:
print('Hessenberg Matrix\n', hess)

Hessenberg Matrix
 [[  1.    -10.731   1.352  -0.147]
 [-10.344   6.495   3.686  -2.915]
 [ -0.      2.358  -5.424   0.489]
 [  0.     -0.     -1.444   3.928]]
