In [20]:
import numpy as np

In [21]:
# matrix = np.array([[-2, 1, 3, 7], [-3, 0, 1, 0], [-2, -1, 0, -2]]) #sample matrix
# matrix = np.array([[-2, 1, 2], [0, -2, 2], [2, -3, 0], [6, -5, -4]])
matrix = np.random.randint(0, 10, size=(4, 4))
print(matrix)

[[4 8 7 7]
 [2 1 6 4]
 [8 3 4 2]
 [2 6 8 1]]


In [22]:
def decompositionLU(matrix):
    U = matrix.astype('float')
    num_rows = U.shape[0]
    P = np.identity(num_rows)
    L = np.identity(num_rows)
    row_switch = 1 #tracks the row switch/ changes in determinant sign
    for row in range(num_rows-1):
        pivot_row = np.argmax(np.abs(U[row:, row])) # find the available row with highest numerical value
        if pivot_row != 0: # if row changes
            row_switch *= -1 # determinant of the inverse permutation matrix
            pivot = pivot_row + row # keep track of the pivot from the current row
            # swap the current rows to the pivot found
            P[[row, pivot]] = P[[pivot, row]]
            L[[row, pivot], :row] = L[[pivot, row], :row]
            U[[row, pivot]] = U[[pivot, row]]
        # subtract the current row by the pivot row (scaled by a factor) to result in a zero
        factor = U[row+1:num_rows, row]/U[row, row]
        U[row+1:num_rows] -= factor.reshape(-1,1) * U[row]
        L[row+1:num_rows, row] = factor
    return P, L, U, row_switch

In [23]:
P, L, U, row_switch = decompositionLU(matrix)
print('Permutation\n', P,'\nLower\n', np.around(L, 3), '\nUpper\n', np.around(U, 3))  # round float to nearest 3 decimal place

Permutation
 [[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]] 
Lower
 [[1.    0.    0.    0.   ]
 [0.5   1.    0.    0.   ]
 [0.25  0.038 1.    0.   ]
 [0.25  0.808 0.616 1.   ]] 
Upper
 [[ 8.     3.     4.     2.   ]
 [ 0.     6.5    5.     6.   ]
 [ 0.     0.     4.808  3.269]
 [ 0.     0.    -0.    -6.36 ]]


Computing for the determinant: $|A| = |P^{-1}||L||U|$

In [24]:
if matrix.shape[0] == matrix.shape[1]: # if square matrix
    # getting the determinant from the product of the diagonals of the resulting matrix from gaussian and the sign change during row switch
    determinant = row_switch*np.product(np.diagonal(U)) # note that the determinant of L matrix has a value of 1
    print('The computed determinant is: ', determinant)
    print('The actual determinant is: ', np.linalg.det(matrix))
else:
    print('The Matrix does not have a determinant')

The computed determinant is:  -1590.0000000000002
The actual determinant is:  -1589.9999999999989


The original matrix can be obtained by doing a matrix multiplication of the Permutation inverse, Lower and Upper

In [25]:
resultFloat = np.linalg.inv(P) @ L @ U
resultMatrix = np.around(resultFloat, 3) # round float to nearest 3 decimal place
print('Original Matrix\n', matrix, '\nResulting Matrix\n', resultMatrix)

Original Matrix
 [[4 8 7 7]
 [2 1 6 4]
 [8 3 4 2]
 [2 6 8 1]] 
Resulting Matrix
 [[4. 8. 7. 7.]
 [2. 1. 6. 4.]
 [8. 3. 4. 2.]
 [2. 6. 8. 1.]]
