In [1]:
import numpy as np
np.set_printoptions(precision=3, suppress=True) # Round the results to 3 decimal place

In [2]:
def decompositionQR(matrix):
    A = matrix.astype('float')
    num_rows, num_columns = matrix.shape
    P = np.identity(num_columns)
    Q = np.zeros((num_rows, 1))
    # np.argsort return the index of ascending elements and np.flip reverse the order
    pivoting = np.flip(np.argsort(np.linalg.norm(A, axis=0))) # Column pivoting
    A = A[:, pivoting]
    P = P[:, pivoting]
    Q[:, 0] = A[:, 0] / np.linalg.norm(A[:, 0]) # Calculates the initial orthonormal vector
    for column in range(1, min(num_rows, num_columns)): # The min function takes care of rectangular matrix
        P_Q = Q[:, :column] @ Q[:, :column].T
        p = P_Q @ A[:, [column]] # Projection of the current column
        e = A[:, [column]] - p # Orthogonal vector
        Q = np.hstack((Q, e / np.linalg.norm(e))) # Append the resulting orthonormal vector
    R = Q.T @ A # Calculate the upper triangular matrix, Q^-1 = Q^T since Q is orthogonal matrix
    return P, Q, R

In [3]:
matrix = np.array([[2/100, 4/100, -1/100, 5/100, 7/100], [1, 2, 3, 4, 5], [100, 45, 16, 32, 64]]).T #sample matrix
print('Original Matrix\n', matrix)

Original Matrix
 [[  0.02   1.   100.  ]
 [  0.04   2.    45.  ]
 [ -0.01   3.    16.  ]
 [  0.05   4.    32.  ]
 [  0.07   5.    64.  ]]


In [4]:
P, Q, R, = decompositionQR(matrix)

In [5]:
print('Permutation Matrix\n', P)
print('Q Matrix\n', Q)
print('R Matrix\n', R)
print('Resulting Matrix\n', Q @ R @ P.T)

Permutation Matrix
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
Q Matrix
 [[ 0.758 -0.556 -0.241]
 [ 0.341  0.043  0.285]
 [ 0.121  0.448 -0.858]
 [ 0.243  0.518  0.196]
 [ 0.485  0.468  0.292]]
R Matrix
 [[131.913   5.2     0.074]
 [ -0.      5.287   0.045]
 [ -0.      0.      0.045]]
Resulting Matrix
 [[  0.02   1.   100.  ]
 [  0.04   2.    45.  ]
 [ -0.01   3.    16.  ]
 [  0.05   4.    32.  ]
 [  0.07   5.    64.  ]]


QR Decomposition using built-in function (for validation purpose)

In [6]:
import scipy as sp
q, r, p = sp.linalg.qr(matrix, pivoting=True)
p = np.identity(r.shape[1])[:, p]

In [7]:
print('Permutation Matrix\n', p)
print('Q Matrix\n', q)
print('R Matrix\n', r)
print('Resulting Matrix\n', q @ r @ p.T)

Permutation Matrix
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
Q Matrix
 [[-0.758  0.556 -0.241  0.236  0.045]
 [-0.341 -0.043  0.285 -0.573 -0.687]
 [-0.121 -0.448 -0.858 -0.187 -0.112]
 [-0.243 -0.518  0.196  0.711 -0.359]
 [-0.485 -0.468  0.292 -0.275  0.62 ]]
R Matrix
 [[-131.913   -5.2     -0.074]
 [   0.      -5.287   -0.045]
 [   0.       0.       0.045]
 [   0.       0.       0.   ]
 [   0.       0.       0.   ]]
Resulting Matrix
 [[  0.02   1.   100.  ]
 [  0.04   2.    45.  ]
 [ -0.01   3.    16.  ]
 [  0.05   4.    32.  ]
 [  0.07   5.    64.  ]]
